### ISSUE TITLE
CMD + R highlighted text is in black

### ISSUE THREAD

**Issue by iCodeForBananas** [smlombardi/slime#1]
I just installed this and love how easy the colors are on my eyes.  However when I push CMD + R and type a function name the matched text is black and unreadable.

Your CMD + T colors work perfectly though.

![screen shot 2015-12-14 at 11 20 26 am](https://cloud.githubusercontent.com/assets/8272012/11791198/ca568c1a-a254-11e5-86e3-f6c9f9dcfaf0.png)

**Comment by smlombardi** [comment]
I need to find a js file with symbols, it seems none of mine have any,
