### ISSUE TITLE
Deprecation warnings with Atom v1.13.0

### ISSUE THREAD

**Issue by michaeldzjap** [smlombardi/slime#3]
Straight from the Atom Deprecation Cop:

> Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--.

**Comment by smlombardi** [comment]
Fixed in https://github.com/smlombardi/slime/commit/931301678e2b4bee726e856c03451edc5d5e1779

**Comment by michaeldzjap** [comment]
Nice one! Thanks
