### ISSUE TITLE
Slime 2.0, no colors anymore?

### ISSUE THREAD

**Issue by ghost** [smlombardi/slime#4]
I just updated to slime 2.0 and all colors for all file types are gone. Anyone has a similar issue? I'm using Atom 1.11.2 on Archlinux.

**Comment by machinek56** [comment]
I have the same issue. Atom 1.12.9, Ubuntu 16.04.

**Comment by 10Ninjas** [comment]
Yes I just updated and no color.

**Comment by smlombardi** [comment]
It will only work on Atom 1.13 and higher.  They changed the syntax naming, so I have to update everything to the new syntax.

**Comment by 10Ninjas** [comment]
I upgraded to Atom 1.13 and slime works now. Thank you!
