### ISSUE TITLE
unterminated string in javascript makes code unreadable

### ISSUE THREAD

**Issue by ghost** [smlombardi/slime#7]
Please take a look on the screen below. It's happens sometimes a string is missing the ending qoutes when you refactor code, then the code is almost unreadable.

![slime_unterminated_string](https://user-images.githubusercontent.com/1245499/29753520-9daeca4c-8b73-11e7-83e9-c98fee14c4fd.png)

**Comment by smlombardi** [comment]
Code is probably flagging that text as invalid.

Can you put your cursor inside this and run the command "Developer: Inspect TM Scopes" and tell me what you see?

You should see a popup like this one (with different content):

<img width="531" alt="screen shot 2017-08-28 at 8 50 07 am" src="https://user-images.githubusercontent.com/835148/29774016-f32291a2-8bcd-11e7-8edd-7d551dbd9254.png">

**Comment by ghost** [comment]
I just inspect it and believe found the issue.

I've changed the CSS selector from `.syntax--invalid` to `.syntax--string .syntax--invalid` and text appears now white, much better readable.
```css
.syntax--string .syntax--invalid {
    color: #F8F8F0;
    background-color: #00A8C6;
}

**Comment by ghost** [comment]
@smlombardi I just noticed you stoppend supporting this theme. I'm interested to take over the project or help with maintenance, whatever you prefer.

**Comment by smlombardi** [comment]
I published a new version with your fix.  Thanks again.
